### ISSUE TITLE
Make DIRT support Weak perspective Camera?

### ISSUE THREAD

**Issue by Frank-Dz** [pmh47/dirt#64]
Hi~ @pmh47 is there any plan to make DIRT support a weak-perspective camera model?

Thanks!
Best,
Frank

**Comment by pmh47** [comment]
No, but it is easy to do yourself. Two possible ways:
- define a suitable projection matrix -- rotation (for orthographic projection part) then scale. Ensure that the clip-space `w` coordinate of the result is one, so OpenGL's perspective division does not do anything. If you have more than one object, and they have different depths, then use one scaling matrix per object.
- cheat: scale your object along the camera-z-axis by a factor slightly larger than zero, large enough that the z-order is still correct, but small enough that the perspective between the near and far parts of the object is (almost) zero. Then use the usual perspective projection matrix.

**Comment by Frank-Dz** [comment]
OK! I will make it.




On 04/26/2020 20:04, Paul Henderson wrote:

No, but it is easy to do yourself. Two possible ways:

define a suitable projection matrix -- rotation (for orthographic projection part) then scale. Ensure that the clip-space w coordinate of the result is one, so OpenGL's perspective division does not do anything. If you have more than one object, and they have different depths, then use one scaling matrix per object.
cheat: scale your object along the camera-z-axis by a factor slightly larger than zero, large enough that the z-order is still correct, but small enough that the perspective between the near and far parts of the object is (almost) zero. Then use the usual perspective projection matrix.

**Comment by Frank-Dz** [comment]
I also have a question about how to render multiple objects in DIRT. At issue #65.

Can you give me some advice?
Thanks!




On 04/26/2020 23:30, Zhiyang-Dou wrote:
OK! I will make it.




On 04/26/2020 20:04, Paul Henderson wrote:

No, but it is easy to do yourself. Two possible ways:

define a suitable projection matrix -- rotation (for orthographic projection part) then scale. Ensure that the clip-space w coordinate of the result is one, so OpenGL's perspective division does not do anything. If you have more than one object, and they have different depths, then use one scaling matrix per object.
cheat: scale your object along the camera-z-axis by a factor slightly larger than zero, large enough that the z-order is still correct, but small enough that the perspective between the near and far parts of the object is (almost) zero. Then use the usual perspective projection matrix.

**Comment by OOF-dura** [comment]
> No, but it is easy to do yourself. Two possible ways:
> 
> * define a suitable projection matrix -- rotation (for orthographic projection part) then scale. Ensure that the clip-space `w` coordinate of the result is one, so OpenGL's perspective division does not do anything. If you have more than one object, and they have different depths, then use one scaling matrix per object.
> * cheat: scale your object along the camera-z-axis by a factor slightly larger than zero, large enough that the z-order is still correct, but small enough that the perspective between the near and far parts of the object is (almost) zero. Then use the usual perspective projection matrix.

Hi~ Dear Paul, I am still a little confused about setting the matrix. For a weak-perspective camera, the projection from one Point in 3D [X,Y] to 2D [x,y] should be defined as:
![image](https://user-images.githubusercontent.com/22954901/80691232-8cffef00-8b02-11ea-84c4-b621517667e9.png)

I do not fully understand the pipeline you provided. Am I missing something? 
Thanks!

**Comment by pmh47** [comment]
Vertex locations passed to DIRT's rasterise operations are 4D vectors (x_c, y_c, z_c, w_c) in OpenGL's clip space. To project them onto screen coordinates (x_s, y_s) in range [-1, 1], the rasteriser does (x_s, y_s) = (x_c / w_c, y_c / w_c). (x_c, y_c, z_c, w_c) are calculated in the user's tensorflow code by the view-space coordinates (x_v, y_v, z_v, 1) multiplied by the projection matrix (which typically sets w_c = -z_v, as the camera by convention looks along negative z axis).

To make a weak perspective camera, you need to set up the projection matrix such that the overall effect of the above pipeline is to reproduce the equation you quoted. If you have just one object, and so all vertices share the same value of Z_ave, then the projection matrix is
```
[
    [f, 0, 0, 0],
    [0, f, 0, 0],
    [0, 0, -(far + near) / (far - near), -2. * far * near / (far - near)],
    [0, 0, 0, -Z_ave]
].T
```
Note that again I used the standard OpenGL convention that the camera looks along the *negative* z-axis, meaning the view-space z_v and Z_ave are negative for the object to be visible!

The transpose accounts for the fact that DIRT uses a vector-times-matrix multiplication convention (not matrix-times-vector as is common in OpenGL).

The first, second and fourth rows do what I described. The third ensures that the depth range is set so the depth-ordering of faces within the object is correct: `far` is a large distance (e.g. twice as far as your scene's farthest vertex distance); `near` is a small distance (e.g. 0.1 * your scene's nearest vertex distance).

Note the units of `f` may need adjusting, depending what convention you use elsewhere.

The important difference to the full perspective projection matrix is that in the bottom row, the fixed depth Z_ave is used, instead of the view-space z coordinate z_v.

If you have multiple objects, they typically have different values of Z_ave, so use different projection matrices of this type.

Actually this is a little different to the two methods I said in the other post (and hopefully more intuitive), but they should all give the same results.

**Comment by Frank-Dz** [comment]
Hi~ @pmh47 Thank you for your generous help! 
![image](https://user-images.githubusercontent.com/55009565/81192728-22acea00-8fed-11ea-9421-ff31561dcbf9.png)

**Comment by lll-gen** [comment]
@Frank-Dz 
Would you like to share the code for the weak perspective projection？I would appreciate it.
